### PR TITLE
Fix "missing ember-cli-babel" deprecation warning

### PR DESCRIPTION
**Pull request by kpfefferle**
In ember-cli 2.12+:

```
DEPRECATION: Addon files were detected in `/node_modules/ember-cli-timecop/addon`, but no JavaScript preprocessors were found for `ember-cli-timecop`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-timecop`'s `package.json`.
```

This PR adds ember-cli-babel as an NPM dependency per the suggestion made by the deprecation warning.

### CODE REVIEW

**Comment by kpfefferle** [comment]
@matteodepalo Any chance of getting this merged and released to get rid of the deprecation warning in ember-cli 2.12+?

**Comment by kpfefferle** [comment]
Upon further review, this deprecation is more simply fixed by removing the `addon` directory as there were not actually any files added to it.

**Comment by farisj** [comment]
+1

**Comment by matteodepalo** [comment]
Thanks for the PR and sorry for the delay!

**Comment by kpfefferle** [comment]
@matteodepalo Any chance we could get this released to NPM?

**Comment by matteodepalo** [comment]
Published as 1.0.1

**Pull request merged**
